//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowLifeAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicatorEntry
    {
        public int Id { get; set; }
        public int IndicatorId { get; set; }
        public string Value { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Indicator Indicator { get; set; }
    }
}
