//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowLifeAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indicator()
        {
            this.IndicatorEntry = new HashSet<IndicatorEntry>();
        }
    
        public int Id { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> UnitOfMeasurementId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int IndicatorTypeId { get; set; }
        public string Frequency { get; set; }
    
        public virtual IndicatorType IndicatorType { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorEntry> IndicatorEntry { get; set; }
    }
}
