//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowLifeAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public int PrescriptionId { get; set; }
        public Nullable<int> ItemTypeId { get; set; }
        public string Frencuency { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> DurationInDays { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ItemType ItemType { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
