//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowLifeAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int Id { get; set; }
        public int DoctorId { get; set; }
        public int PrescriptionTypeId { get; set; }
        public string Frencuency { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> DurationInDays { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int PatientId { get; set; }
        public string Status { get; set; }
        public System.DateTime FinishedAt { get; set; }
        public System.DateTime StartedAt { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual PrescriptionType PrescriptionType { get; set; }
    }
}
